### ISSUE TITLE
[タスク] ローカルDBを実装する

### ISSUE THREAD

**Issue by p238049y** [p238049y/todoappByFlutter#21]
### 方針
ローカルDBの実装を行い、最終目標としては以下の手順を踏めるようにしたい

* 処理の流れ
  1. ADD をクリックする
  2. ローカルDBに保存する
  3.  Navigator.of(context).popUntil((route) => route.isFirst);　でTodoListPageに戻る
  4. TodoListPageでローカルDBにアクセスし必要な情報を取得する
 

![image](https://user-images.githubusercontent.com/82100625/184505671-f66018f9-a133-48c2-8544-52083271cfb2.png)

### 参考文献
* [SQLiteについてと導入方法](https://www.flutter-study.dev/recipe/local-data)

**Comment by p238049y** [comment]
ローカルDBを使う上でpathというパッケージをインストールする必要がある。
path パッケージは、結合、分割、正規化など、パスを操作するための一般的な操作をするために必要

参考文献：https://pub.dev/packages/path

**Comment by p238049y** [comment]
### エラー

```dart
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=1 "table todo has no column named todo_title" UserInfo={NSLocalizedDescription=table todo has no column named todo_title}) sql 'INSERT INTO todo (todo_title, detail_information, elapsed_time, target_time, created_at) VALUES (?, ?, ?, ?, ?)' args [AAA, AAAA, , 01:00, 2022-08-26 21:02:13.408018]
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
<asynchronous suspension>
#1      SqfliteDatabaseMixin.txnRawInsert.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:392:14)
<asynchronous suspension>
#2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
<asynchronous suspension>
#3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:344:14)
<asynchronous suspension>
#4      DbProvider.insertData (package:mytodoapp/DB/sqflite.dart:30:5)
<asynchronous suspension>
#5      _TimerPage.build.<anonymous closu<…>
```

**Comment by p238049y** [comment]
### エラーの原因解明
* 以下のコードが正常に動くことで、再度DBのマイグレーションが働かないようにしている
* リロードしただけではカラムは追加されない

```dart
  static Future<Database?> setDb() async {
    if (database == null) {
      database = await initDb();
      return database;
    } else {
      return database;
    }
  }
```

### 対応方針
* １度アプリを削除し、再度ビルドし直すことでマイグレーションを再度動かす

**Comment by p238049y** [comment]
エラーがなく動くことを確認

https://user-images.githubusercontent.com/82100625/186907117-0f2e4f42-42ee-4c38-8645-70ba6d4228eb.mov

**Comment by p238049y** [comment]
### 動作確認
以下の処理が動作していることを確認した

```
1. ADD をクリックする
2. ローカルDBに保存する
3. Navigator.of(context).popUntil((route) => route.isFirst);　でTodoListPageに戻る
4. TodoListPageでローカルDBにアクセスし必要な情報を取得する
```

https://user-images.githubusercontent.com/82100625/187954293-7680932c-0b07-4f58-90c4-94f6acc3a988.mov
