### ISSUE TITLE
[タスク] タイマー画面を作成する

### ISSUE THREAD

**Issue by p238049y** [p238049y/todoappByFlutter#9]
> タイマーの実装

https://zenn.dev/kyo9bo/articles/982e3b4c92eeb2

https://zenn.dev/mukkun69n/articles/67e35ffc797f12

https://lab.astamuse.co.jp/entry/flutter-timer-app

https://px-wing.hatenablog.com/entry/2022/07/14/084814
→ このデザイン良さそう

**Comment by p238049y** [comment]
NumberPickerについて

https://pub.dev/packages/numberpicker
https://kohshin1977.com/?p=158

**Comment by p238049y** [comment]
こんなイメージ
![image](https://user-images.githubusercontent.com/82100625/180221699-2326caf2-fba7-4333-9394-a2e39c5c47cc.png)

**Comment by p238049y** [comment]
* スタートボタンをクリックするとエラーとなってしまった

![image](https://user-images.githubusercontent.com/82100625/181248717-aa272b6c-dc23-4993-bedb-6e46f42bf6ca.png)


```dart
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.
Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
├# Here is the subtree for one of the offending heroes: Hero

When the exception was thrown, this was the stack:
#0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:271:11)
#1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:282:8)
#2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:301:11)
#3      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#6      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#8      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#10     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#11     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6314:16)
#12     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#14     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#16     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#18     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#20     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#21     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6314:16)
#22     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#24     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#26     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#28     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#29     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6314:16)
#30     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#32     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#34     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#36     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#38     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#40     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#41     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#42     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#44     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#45     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#46     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#48     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#50     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#51     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#52     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#54     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#56     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#57     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#58     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#60     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4859:14)
#62     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:316:15)
#63     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6202:14)
#64     Element.visitChildElements (package:flutter/src/widgets/framework.dart:3429:5)
#65     Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:319:13)
#66     HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:925:14)
#67     HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:884:11)
#68     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#69     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1091:9)
#70     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#74     _invoke (dart:ui/hooks.dart:151:10)
#75     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#76     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

### 対応方針
* 2つ以上のFloatingActionButton(FAB)を使って、画面遷移しようとすると例外が投げられる
* 解決策は、UniqueなheroTagを設定すること
* 基本的にMaterial designでは1画面につき1つだけFABの使用を推奨している

### 参考文献
https://qiita.com/rei_012/items/c07e95b5793d943229e3
https://www.miajimyu.com/docs/flutter/flutter-two-floating-action-button/

**Comment by p238049y** [comment]
### バグ
* スタートボタンをクリックしてもタイマーが作動しない。。。
![スクリーンショット 2022-07-21 22 11 11](https://user-images.githubusercontent.com/82100625/181261094-52942e56-22af-4117-b39b-c44d3c8b98b7.png)

### 対応方針
* どうやら、メソッドの書き方にはいくつかあるらしい。
* 自分のコードでは以下のように書かなければならない

```dart
// OK
onPressed: model.isStartPressed ? model.startTimer : null,

// NG
onPressed: model.isStartPressed ? model.startTimer() : null,
```

### 参考文献
https://zenn.dev/sakusin/articles/3de0430c030c99

**Comment by p238049y** [comment]
> タイマーの残り時間の表記が秒単位であること
残り時間はHH:MM:SSで表記したい
startボタンを押すまで時間を設定できないこと
０秒になったことがわかりにくい　-> 別課題

上記を解決し、終了
https://user-images.githubusercontent.com/82100625/181934032-b1dde685-0744-4b35-a895-83f765f79fd0.mov

**Comment by p238049y** [comment]
### 解決
> タイマーの残り時間の表記が秒単位であること
残り時間はHH:MM:SSで表記したい
startボタンを押すまで時間を設定できないこと
０秒になったことがわかりにくい　-> 別課題


https://user-images.githubusercontent.com/82100625/181934092-2811dd3b-9c2d-4750-8d6b-ee1e84527eb0.mov

**Comment by p238049y** [comment]
このチケットは終了
